# PcCTP - CTP API Python 绑定
# 自动生成文件，请勿手动修改
# 模块常量
# =============================================================================

# PcCTP 模块版本号
__version__ = 'v测试版本0.1.0'
# CTP 接口版本号
__ctp_version__ = 'v6.7.11_20250714'
# 采集库fix版本号
__fix_version__ = 'sfit_pro_1.0_20220124_1468'
# 运行平台
__platform__ = 'win64'
# 版本类型
__version_type__ = 'PC'

__full_version__ = 'PcCTP v测试版本0.1.0 | CTP v6.7.11_20250714 | FIX sfit_pro_1.0_20220124_1468 | PC | win64'
import platform
import os
from PcCTP.interface import *
# 获取操作系统类型
def get_os_type():
    """获取操作系统类型: win64, win32, linux, macos, 或其他"""
    system = platform.system().lower()
    if system == "windows":
        # 通过环境变量检测系统架构
        arch_env = os.environ.get('PROCESSOR_ARCHITECTURE', '')
        arch_env_w6432 = os.environ.get('PROCESSOR_ARCHITEW6432', '')
        if 'AMD64' in (arch_env, arch_env_w6432):
            return 'win64'
        else:
            return 'win32'
    elif system == "linux":
        return 'linux'
    elif system == "darwin":
        return 'macos'
    else:
        return 'other'

# 调用方法获取当前系统类型
env = get_os_type()

# 通过系统类型导入对应的接口
if env == 'win64':  # windows64位
    from PcCTP.win64 import *
    print('导入PyCTP')
elif env == 'win32':  # windows32位
    from PcCTP.win32 import *
elif env == 'linux':  # linux
    from PcCTP.linux import *
else:  # 其他系统 暂不支持,如：macOS
    raise EnvironmentError('本CTP版本与当前系统不匹配')

# 导入所有枚举类（支持 from win64 import Direction, OffsetFlag 等）
from PcCTP.enums import *
from PcCTP.types import *

# 定义__all__列表，包含所有导出的名称
__all__ = [
    # 枚举类
    "AMLCheckStatus",
    "AMLGenStatus",
    "APIProductClass",
    "AccountSettlementParamID",
    "AccountSourceType",
    "ActionDirection",
    "ActionFlag",
    "ActionType",
    "ActiveType",
    "AlgoType",
    "Algorithm",
    "AllWithoutTrade",
    "AmType",
    "AmlCheckLevel",
    "AmlDateType",
    "AppType",
    "ApplyOperateID",
    "ApplyStatusID",
    "ApplyType",
    "AssetmgrClientType",
    "AssetmgrType",
    "AuthType",
    "AvailabilityFlag",
    "BackUpStatus",
    "BalanceAlgorithm",
    "BalanceType",
    "BankAccStatus",
    "BankAccType",
    "BankAccountOrigin",
    "BankRepealFlag",
    "BasisPriceType",
    "BatchStatus",
    "BillGenStatus",
    "BillHedgeFlag",
    "BizType",
    "BrokerDataSyncStatus",
    "BrokerFunctionCode",
    "BrokerRepealFlag",
    "BrokerType",
    "BrokerUserType",
    "BusinessClass",
    "BusinessType",
    "ByGroup",
    "ByInvestorRange",
    "CCBFeeMode",
    "CFFEXUploadFileName",
    "CFMMCKeyKind",
    "CSRCDataQueryType",
    "CSRCFundIOType",
    "CTPType",
    "CZCEUploadFileName",
    "CashExchangeCode",
    "CertificationType",
    "CfmmcReturnCode",
    "CheckInstrType",
    "CheckLevel",
    "CheckStatus",
    "ClassType",
    "ClientIDStatus",
    "ClientIDType",
    "ClientRegion",
    "ClientType",
    "CloseDealType",
    "CloseStyle",
    "CodeSourceType",
    "CombDirection",
    "CombinationType",
    "CommApiType",
    "ConditionalOrderSortType",
    "ConnectMode",
    "ContingentCondition",
    "CurrExDirection",
    "CurrencySwapStatus",
    "CusAccountType",
    "CustType",
    "DAClientType",
    "DBOperation",
    "DCEUploadFileName",
    "DataResource",
    "DataStatus",
    "DataSyncStatus",
    "DceCombinationType",
    "DeliveryMode",
    "DeliveryType",
    "DepartmentRange",
    "Direction",
    "DirectionEn",
    "EnumBool",
    "EventMode",
    "ExClientIDType",
    "ExDirection",
    "ExStatus",
    "ExchangeConnectStatus",
    "ExchangeIDType",
    "ExchangeProperty",
    "ExchangeSettlementParamID",
    "ExecOrderCloseFlag",
    "ExecOrderPositionFlag",
    "ExecResult",
    "ExportFileType",
    "ExprSetMode",
    "FBEAlreadyTrade",
    "FBEExchStatus",
    "FBEFileFlag",
    "FBEReqFlag",
    "FBEResultFlag",
    "FBEUserEventType",
    "FBTEncryMode",
    "FBTPassWordType",
    "FBTTradeCodeEnum",
    "FBTTransferDirection",
    "FBTUserEventType",
    "FeeAcceptStyle",
    "FeePayFlag",
    "FileBusinessCode",
    "FileFormat",
    "FileGenStyle",
    "FileID",
    "FileStatus",
    "FileType",
    "FileUploadStatus",
    "FindMarginRateAlgoID",
    "FlexStatMode",
    "FlowID",
    "ForQuoteStatus",
    "ForceCloseReason",
    "ForceCloseType",
    "FreezeStatus",
    "FunctionCode",
    "FundDirection",
    "FundDirectionEn",
    "FundEventType",
    "FundIOType",
    "FundIOTypeEn",
    "FundMortDirection",
    "FundMortDirectionEn",
    "FundMortgageType",
    "FundStatus",
    "FundType",
    "FundTypeEn",
    "FutureAccType",
    "FuturePwdFlag",
    "FutureType",
    "Gender",
    "GiveUpDataSource",
    "HandlePositionAlgoID",
    "HandleTradingAccountAlgoID",
    "HasBoard",
    "HasTrustee",
    "HedgeFlag",
    "HedgeFlagEn",
    "IdCardType",
    "IncludeCloseProfit",
    "InitSettlement",
    "InstLifePhase",
    "InstMarginCalID",
    "InstStatusEnterReason",
    "InstitutionType",
    "InstrumentClass",
    "InstrumentStatus",
    "InvestTradingRight",
    "InvestorRange",
    "InvestorRiskStatus",
    "InvestorSettlementParamID",
    "InvestorType",
    "LanguageType",
    "LastFragment",
    "LimitUseType",
    "LinkStatus",
    "LoginMode",
    "ManageStatus",
    "MarginPriceType",
    "MarginRateType",
    "MarginType",
    "MarketMakeState",
    "MatchType",
    "MaxMarginSideAlgorithm",
    "MoneyAccountStatus",
    "MonthBillTradeSum",
    "MortgageFundUseRange",
    "MortgageType",
    "NoteType",
    "NotifyClass",
    "OTCTradeType",
    "OTPStatus",
    "OTPType",
    "OffsetFlag",
    "OffsetFlagEn",
    "OffsetType",
    "OpenLimitControlLevel",
    "OpenOrDestroy",
    "OptSelfCloseFlag",
    "OptionRoyaltyPriceType",
    "OptionsType",
    "OrderActionStatus",
    "OrderCancelAlg",
    "OrderFreqControlLevel",
    "OrderPriceType",
    "OrderSource",
    "OrderStatus",
    "OrderSubmitStatus",
    "OrderType",
    "OrgSystemID",
    "OrganLevel",
    "OrganStatus",
    "OrganType",
    "ParkedOrderStatus",
    "PassWordKeyType",
    "PasswordType",
    "PersonType",
    "PortfType",
    "Portfolio",
    "PositionDate",
    "PositionDateType",
    "PositionDirection",
    "PositionType",
    "PriceSource",
    "ProcessStatus",
    "ProdChangeFlag",
    "ProductClass",
    "ProductLifePhase",
    "ProductStatus",
    "ProductType",
    "PromptType",
    "PropertyInvestorRange",
    "ProtocolID",
    "PublishStatus",
    "PwdFlag",
    "PwdRcdSrc",
    "QueryInvestorRange",
    "QuestionType",
    "RCAMSCombinationType",
    "RateInvestorRange",
    "RateType",
    "RatioAttr",
    "Reason",
    "ReportStatus",
    "ReqFlag",
    "ReqRspType",
    "ResFlag",
    "ReserveOpenAccStas",
    "ResponseValue",
    "ReturnLevel",
    "ReturnPattern",
    "ReturnStandard",
    "ReturnStyle",
    "RightParamType",
    "RiskLevel",
    "RiskNotifyMethod",
    "RiskNotifyStatus",
    "RiskUserEvent",
    "SHFEUploadFileName",
    "SaveStatus",
    "SecuAccType",
    "SendMethod",
    "SendType",
    "SettArchiveStatus",
    "SettleManagerGroup",
    "SettleManagerLevel",
    "SettleManagerType",
    "SettlementBillType",
    "SettlementStatus",
    "SettlementStyle",
    "Sex",
    "SpecPosiType",
    "SpecProductType",
    "SpecialCreateRule",
    "SponsorType",
    "StandardStatus",
    "StartMode",
    "StatMode",
    "StrikeMode",
    "StrikeOffsetType",
    "StrikeType",
    "SwapSourceType",
    "SyncDataStatus",
    "SyncDeltaStatus",
    "SyncFlag",
    "SyncMode",
    "SyncType",
    "SysOperMode",
    "SysOperType",
    "SysSettlementStatus",
    "SystemParamID",
    "SystemStatus",
    "SystemType",
    "TemplateType",
    "TimeCondition",
    "TimeRange",
    "TradeParamID",
    "TradeSource",
    "TradeSumStatMode",
    "TradeType",
    "TraderConnectStatus",
    "TradingRight",
    "TradingRole",
    "TradingType",
    "TransferDirection",
    "TransferStatus",
    "TransferType",
    "TransferValidFlag",
    "TxnEndFlag",
    "UOAAssetmgrType",
    "UOAAutoSend",
    "UpdateFlag",
    "UsedStatus",
    "UserEventType",
    "UserRange",
    "UserRightType",
    "UserType",
    "ValueMethod",
    "VirBankAccType",
    "VirDealStatus",
    "VirTradeStatus",
    "VirementAvailAbility",
    "VirementStatus",
    "VirementTradeCode",
    "VolumeCondition",
    "WeakPasswordSource",
    "WithDrawParamID",
    "YesNoIndicator",
    # 方法
    "validate_direction", "validate_offset_flag",
    "validate_order_price_type", "get_direction_name",
    "get_offset_flag_name",
    # 错误码映射
    "reason_map",
    # 字符串池监控和清理函数
    "cleanup_temporal_pools", "cleanup_instruments",
    "check_instrument_pool_size", "get_pool_sizes",
    # 核心类（1个）
    "MdApi",
    # TypedDict（9个）
    "DepthMarketData",
    "FensUserInfo",
    "ForQuoteRsp",
    "MulticastInstrument",
    "QryMulticastInstrument",
    "ReqUserLogin",
    "RspInfo",
    "RspUserLogin",
    "UserLogout",
]
