from typing import Optional, Protocol
from .types import (
    DepthMarketData, ForQuoteRsp, MulticastInstrument, RspUserLogin, RspInfo, UserLogout,
    # 交易API相关类型

)


class PyMdSpi(Protocol):
    """
    CTP PC版行情回调接口协议（Protocol）

    使用 Protocol 而非 ABC 的优势：
    - 不需要显式继承
    - 任何实现相应方法的类都会被识别为兼容类型
    - 更符合 Python 的鸭子类型理念
    - IDE 类型检查更准确

    使用示例：
        class MySpi:  # 不需要继承 PyMdSpi
            def on_front_connected(self) -> None: ...
            # 实现其他方法...

        api.register_spi(MySpi())  # 类型检查通过
    """

    def on_front_connected(self) -> None: ...
    def on_front_disconnected(self, reason: int) -> None: ...
    def on_heart_beat_warning(self, time_lapse: int) -> None: ...
    def on_rsp_user_login(self, rsp_user_login: RspUserLogin, rsp_info: RspInfo, request_id: int, is_last: bool) -> None: ...
    def on_rsp_user_logout(self, user_logout: UserLogout, rsp_info: RspInfo, request_id: int, is_last: bool) -> None: ...
    def on_rsp_error(self, rsp_info: RspInfo, request_id: int, is_last: bool) -> None: ...
    def on_rsp_sub_market_data(self, instrument_id: Optional[str], rsp_info: RspInfo, request_id: int, is_last: bool) -> None: ...
    def on_rsp_un_sub_market_data(self, instrument_id: Optional[str], rsp_info: RspInfo, request_id: int, is_last: bool) -> None: ...
    def on_rsp_sub_for_quote_rsp(self, instrument_id: Optional[str], rsp_info: RspInfo, request_id: int, is_last: bool) -> None: ...
    def on_rsp_un_sub_for_quote_rsp(self, instrument_id: Optional[str], rsp_info: RspInfo, request_id: int, is_last: bool) -> None: ...
    def on_rtn_depth_market_data(self, depth_market_data: DepthMarketData) -> None: ...
    def on_rtn_for_quote_rsp(self, for_quote_rsp: ForQuoteRsp) -> None: ...
    def on_rsp_qry_multicast_instrument(self, multicast_instrument: Optional[MulticastInstrument], rsp_info: RspInfo, request_id: int, is_last: bool) -> None: ...